sudo: required

dist: xenial

language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - BUILDKIT_HOST=tcp://0.0.0.0:1234
    - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - chmod +x ./.travis/setup.sh
  - chmod +x ./.travis/build.sh
  - ./.travis/setup.sh

jobs:
  include:
    - script: >
        ./.travis/build.sh
