name: Docker CI Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin      
      - 
        name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t nico640/docker-unms:latest -f Dockerfile \
            --push --cache-from type=local,src=/tmp/buildx-cache \
            --cache-to type=local,dest=/tmp/buildx-cache .
