#Legacy armhf tag, use latest for all platforms!
name: Docker CI Legacy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin      
      - 
        name: Build and push Docker image
        run: docker buildx build --platform linux/arm -t nico640/docker-unms:armhf -f Dockerfile --push .
